##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## (C) Copyright 2018-2023 Open Walnoot B.V. (http://openwalnoot.com)                                                  ~
##                                                                                                                     ~
## Licensed under the GNU Lesser General Public License v3.0 (the 'License'). You may not use this file except in      ~
## compliance with the License. You may obtain a copy of the License at: https://choosealicense.com/licenses/lgpl-3.0  ~
## Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on ~
## an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  ~
## specific language governing permissions and limitations under the License.                                          ~
##                                                                                                                     ~
## Maintainers:                                                                                                        ~
##     Wim Bast, Tom Brus                                                                                              ~
## Contributors:                                                                                                       ~
##     Ronald Krijgsheld                                                                                               ~
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: build

on: [ push, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[no-ci]')"
    env:
      ALLREP_TOKEN: "${{secrets.ALLREP_TOKEN}}"
      TOKEN: "${{secrets.ALLREP_TOKEN}}"
      JETBRAINS_PUBLISH_TOKEN: "${{secrets.JETBRAINS_PUBLISH_TOKEN}}"
      CI: "true"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu

      ################################################################################
      - name: "boost memory for gradle"
        run: echo $TOKEN && mkdir ~/.gradle && echo "org.gradle.jvmargs=-Xmx8096m" >> ~/.gradle/gradle.properties

      - name: "bootstrap"
        run: ./gradlew --stacktrace --info --build-file bootstrap.gradle.kts

      - name: "build"
        run: ./gradlew --info --scan
